version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws-dependencies:
        patterns:
          - "github.com/hashicorp/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
