version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - copyloopvar
    - errcheck
    - errname
    - forbidigo
    - govet
    - lll
    - misspell
    - nakedret
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unused
    - usetesting
  settings:
    forbidigo:
      forbid:
        - pattern: t\.Fatal.*
        - pattern: fmt\.Print.*
    govet:
      disable:
        - shadow
      enable-all: true
    lll:
      line-length: 165
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: \.go
        text: 'fieldalignment:'
      - linters:
          - staticcheck
        path: \.go
        text: 'SA1019'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
